version: 0.11.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
artifacts:
- path: Rapr\bin\$(configuration)
  name: DriverStoreExplorer.v$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: DriverStore Explorer v$(appveyor_build_version)
  auth_token:
    secure: DxLf0qbioyNvVmBu8V6t+a5/ARMBmKNUsfDrxe1ARH6p6b493mhUhoIG4SSdrHwiscEoiqU2+WGb3LKgVhxXNglPNprhWVEpuD/48cEEwnv+t8goa7yYnt8l3528MtYO
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
