version: 0.12.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: normal
artifacts:
- path: Rapr\bin\$(configuration)\net462
  name: DriverStoreExplorer.v$(appveyor_build_version)
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: DriverStore Explorer v$(appveyor_build_version)
  auth_token:
    secure: kjDyjFc99PloCToD7DfI3ETVarqB4gjDe8HNYHe8FojFVSDqjmX6XCxP77nzAzFR
  draft: true
  prerelease: false
  force_update: true
  on:
    branch: master
